# Generated by Django 4.0.2 on 2022-02-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_slug',
        ),
    ]
